# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Portfolio"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

props:
  preheading: "Our works"
  heading: "We have done lots of works, lets check some"
  projects:
    - project: "images/portfolio/1.jpg"
      image: "images/portfolio/1.jpg"
      icon: "ti-plus"
      name: "Project california"
      type: "Web Development"
    - project: "images/portfolio/2.jpg"
      image: "images/portfolio/2.jpg"
      icon: "ti-plus"
      name: "Project california"
      type: "Web Development"
    - project: "images/portfolio/3.jpg"
      image: "images/portfolio/3.jpg"
      icon: "ti-plus"
      name: "Project california"
      type: "Web Development"
    - project: "images/portfolio/4.jpg"
      image: "images/portfolio/4.jpg"
      icon: "ti-plus"
      name: "Project california"
      type: "Web Development"
    - project: "images/portfolio/5.jpg"
      image: "images/portfolio/5.jpg"
      icon: "ti-plus"
      name: "Project california"
      type: "Web Development"
    - project: "images/portfolio/6.jpg"
      image: "images/portfolio/6.jpg"
      icon: "ti-plus"
      name: "Project california"
      type: "Web Development"

