# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Team"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

props: 
  preheading: "Our Team"
  heading: "Expert Team member to get best service"
  members:
    - headshot: "/images/team/team-1.jpg"
      facebook: "https://www.facebook.com/themefisher"
      twitter: "https://twitter.com/themefisher"
      instagram: "https://www.instagram.com/themefisher/"
      linkedin: "https://themefisher.com/"
      name: "Justin Yammer"
      role: "Digital Marketer"
    - headshot: "/images/team/team-2.jpg"
      facebook: "https://www.facebook.com/themefisher"
      twitter: "https://twitter.com/themefisher"
      instagram: "https://www.instagram.com/themefisher/"
      linkedin: "https://themefisher.com/"
      name: "Jason Roy"
      role: "UX Designer"
    - headshot: "/images/team/team-3.jpg"
      facebook: "https://www.facebook.com/themefisher"
      twitter: "https://twitter.com/themefisher"
      instagram: "https://www.instagram.com/themefisher/"
      linkedin: "https://themefisher.com/"
      name: "Henry Oswald"
      role: "Developer"
    - headshot: "/images/team/team-4.jpg"
      facebook: "https://www.facebook.com/themefisher"
      twitter: "https://twitter.com/themefisher"
      instagram: "https://www.instagram.com/themefisher/"
      linkedin: "https://themefisher.com/"
      name: "David Williams"
      role: "Senior Marketer"
    - headshot: "/images/team/team-5.jpg"
      facebook: "https://www.facebook.com/themefisher"
      twitter: "https://twitter.com/themefisher"
      instagram: "https://www.instagram.com/themefisher/"
      linkedin: "https://themefisher.com/"
      name: "Peter Odin"
      role: "App Developer"
    - headshot: "/images/team/team-6.jpg"
      facebook: "https://www.facebook.com/themefisher"
      twitter: "https://twitter.com/themefisher"
      instagram: "https://www.instagram.com/themefisher/"
      linkedin: "https://themefisher.com/"
      name: "David Spencer"
      role: "Project Manager"
