# Metadata about this component, to be used in the CMS
[spec]
structures = [ "content_blocks" ]
label = "Counter"
description = ""
icon = ""
tags = []

# Defines the structure of this component, as well as the default values
[blueprint]
text = "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
[preview]

# Any extra CloudCannon inputs configuration to apply to the blueprint
[_inputs]

[props]
[[props.stats]]
value = "1234"
suffix = " +"
tagline = "Projects completed" 

[[props.stats]]
value = "5678"
suffix = "M"
tagline = "Happy Customers"
