# Metadata about this component, to be used in the CMS
[spec]
structures = [ "content_blocks" ]
label = "About"
description = "Overview of the company"
icon = ""
tags = []

# Defines the structure of this component, as well as the default values
[blueprint]


# Overrides any fields in the blueprint when viewing this component in the component browser
[preview]

# Any extra CloudCannon inputs configuration to apply to the blueprint
[_inputs]

[props]
preheading = "Instant gratification"
heading = "We are dynamic team of creative people"
text = "We provide consulting services in the area of IFRS and management reporting, helping
companies to reach their highest level. We optimize business processes, making them easier."
cta = "Get Started"
link = "#"