# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Pricing"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Hello World!"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

props: 
  preheading: "Our Pricing"
  heading: "No hidden Charges.Choose Your Perfect Plan"
  offers: 
    - name: "Free"
      price: "€0"
      metric: "Per User / Month"
      include1: "- Up to 1 User"
      include2: "- Max 100 Items"
      include3: "- 500 Queries"
      include4: "- Basic Statistics"
      button_text: "Download Now"
    - name: "Basic"
      price: "€12"
      metric: "Per User / Month"
      include1: "- Up to 5 Users"
      include2: "- Max 1000 Items"
      include3: "- 5000 Queries"
      include4: "- Standard Statistics"
      button_text: "Signup Now"
    - name: "Premium"
      price: "€39"
      metric: "Per User / Month"
      include1: "- Unlimited User"
      include2: "- Unlimited Items"
      include3: "- Unlimited Queries"
      include4: "- Full Statistics"
      button_text: "Download Now"
  cta_preheading: "For Every type business"
  cta_text: "Entrust Your Project to Our Best Team of Professionals"
  link:
    url: "/contact.html"
    text: "Contact Us"